name: Deploy website to GitHub Pages

env:
  WC_HUGO_VERSION: '0.136.5'

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    if: github.repository_owner != 'HugoBlox'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Validate environment
      run: |
        if [ -z "${{ env.WC_HUGO_VERSION }}" ]; then
          echo "Error: Hugo version not set"
          exit 1
        fi

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ env.WC_HUGO_VERSION }}
        extended: true

    - uses: actions/cache@v3
      with:
        path: /tmp/hugo_cache/
        key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-hugomod-

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v3

    - name: Build with Hugo
      env:
        HUGO_ENVIRONMENT: production
      run: |
        echo "Hugo Cache Dir: $(hugo config | grep cachedir)"
        hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/" || {
          echo "Hugo build failed"
          exit 1
        }

    - name: Debug public directory
      run: |
        echo "Checking public directory..."
        if [ -d "public" ]; then
          echo "Public directory exists"
          echo "Contents of public directory:"
          ls -la public/
          echo "Total size of public directory:"
          du -sh public/
        else
          echo "Error: public directory does not exist!"
          echo "Contents of current directory:"
          ls -la
          exit 1
        fi

    - name: Generate Pagefind search index
      run: npx pagefind --site "public"

    - name: Package artifact
      run: |
        echo "Packaging artifact..."
        tar -czf artifact.tar.gz public/
        echo "Created artifact archive:"
        ls -lh artifact.tar.gz

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: artifact.tar.gz
        name: github-pages

  deploy:
    if: github.repository_owner != 'HugoBlox'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 10
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: github-pages
        
    - name: Unpack artifact
      run: |
        tar -xzf artifact.tar.gz
        ls -la public/
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v3
      with:
        path: public/